name: Build and upload package
on:
  push:
    branches:
    - main
  release:
    types:
    - published
  workflow_dispatch:

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  build:
    name: Build & Verify package
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        fetch-depth: 0

    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: 3.8

    - run: python -m pip install --upgrade pip setuptools_scm build twine

    - name: Force version for Test PyPI upload
      if: ${{ !startsWith(github.ref, 'refs/tags') }}
      run: echo version=$(python -m setuptools_scm | awk -F+ '{print $1}' | tail -1) >> $GITHUB_ENV

    - run: echo 'PKG = "pip"'>dvc/_build.py
    - run: python -m build
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION_FOR_DVC: ${{ env.version }}
    - run: twine check --strict dist/*

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: Packages
        path: dist/

  test-pypi-publish:
    name: Publish dev package to test.pypi.org
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.action == 'published' || (github.repository == 'iterative/dvc' && github.event_name == 'push' && github.ref == 'refs/heads/main') }}

    environment:
      name: test-pypi
      url: https://test.pypi.org/p/dvc

    permissions:
      id-token: write

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: Packages
        path: dist

    - name: Upload package to Test PyPI
      uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

  pypi-publish:
    name: Publish released package to pypi.org
    runs-on: ubuntu-latest
    needs: build
    if: github.event.action == 'published'

    environment:
      name: pypi
      url: https://pypi.org/p/dvc

    permissions:
      id-token: write

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: Packages
        path: dist

    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # release/v1
