name: Remote Plugin Tests

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        pyv: ["3.10"]
        plugin: ["dvc-s3"]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        path: dvc

    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        repository: iterative/${{ matrix.plugin }}
        ref: main
        path: ${{ matrix.plugin }}

    - name: Set up Python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: ${{ matrix.pyv }}
        cache: pip
        cache-dependency-path: |
          dvc/pyproject.toml
          ${{ matrix.plugin }}/setup.cfg

    - name: Install plugin + DVC@PR
      run: |
        pip install --upgrade pip wheel
        pip install "./dvc[testing]"
        pip install -e "./${{ matrix.plugin }}[tests]"

    - name: Run plugin tests
      timeout-minutes: 15
      working-directory: ${{ matrix.plugin }}
      run: pytest -v -n=auto
